### ISSUE TITLE
Cannot use a Char as a HashMap key

### ISSUE THREAD

**Issue by thegridman** [xtclang/xvm#247] opened 2024-11-07 09:17 UTC
If I create a `HashMap<Char, anything>` then I get an exception when I try to put anything into the map.
 
**To Reproduce**
The following code reproduces the error
```
module TestChars {
    void run(String[] args) {
        HashMap<Char, String> map = new HashMap();
        map.put('a', "foo");
    }
}
```

When run the output is:
```
Info: Executing "TestChars" from /Users/jonathanknight/dev/ecsatsy/xvm/manualTests/build/map_of_char.xtc
java.lang.ClassCastException: class org.xvm.runtime.ObjectHandle$JavaLong cannot be cast to class org.xvm.runtime.ObjectHandle$GenericHandle (org.xvm.runtime.ObjectHandle$JavaLong and org.xvm.runtime.ObjectHandle$GenericHandle are in unnamed module of loader 'app')
        at org.xvm.runtime.template.xConst.buildHashCode(xConst.java:444)
        at org.xvm.runtime.template.xConst.callHashCode(xConst.java:434)
        at org.xvm.runtime.template.xConst.invokeNativeN(xConst.java:395)
        at org.xvm.asm.op.Call_N1.process(Call_N1.java:136)
        at org.xvm.runtime.ServiceContext.execute(ServiceContext.java:637)
        at org.xvm.runtime.ServiceContext.drainWork(ServiceContext.java:360)
        at org.xvm.runtime.ServiceContext.execute(ServiceContext.java:411)
        at org.xvm.runtime.Container.lambda$schedule$0(Container.java:163)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
        at java.base/java.lang.Thread.run(Thread.java:1583)

        at collections.NaturalHasher.hashOf(ecstasy:collections.NaturalHasher.Value) (NaturalHasher.x:13)
        at maps.HasherMap.put(ecstasy:maps.HasherMap.Key, ecstasy:maps.HasherMap.Value) (HasherMap.x:804)
        at run(Array<String>) (map_of_char.x:6)
        at ^TestChars (CallLaterRequest: native)


2024-11-07 12:06:11.275 Service "TestChars" (id=1) at ^TestChars (CallLaterRequest: native), fiber 15: Unhandled exception: Exception: Run-time error: java.lang.ClassCastException: class org.xvm.runtime.ObjectHandle$JavaLong cannot be cast to class org.xvm.runtime.ObjectHandle$GenericHandle (org.xvm.runtime.ObjectHandle$JavaLong and org.xvm.runtime.ObjectHandle$GenericHandle are in unnamed module of loader 'app')
        at collections.NaturalHasher.hashOf(ecstasy:collections.NaturalHasher.Value) (NaturalHasher.x:13)
        at maps.HasherMap.put(ecstasy:maps.HasherMap.Key, ecstasy:maps.HasherMap.Value) (HasherMap.x:804)
        at run(Array<String>) (map_of_char.x:6)
        at ^TestChars (CallLaterRequest: native)
```

**Expected behavior**
I expect the code above to work.

**Possible Fix**
Adding the following to `Char` fixes the issue, but this feels wrong as `Char` is a `const` which is supposed to automatically be `Hashable`
```
    // ----- Hashable functions --------------------------------------------------------------------

    @Override
    static <CompileType extends Char> Int64 hashCode(CompileType value) {
        return value.codepoint.hashCode();
    }

    @Override
    static <CompileType extends Char> Boolean equals(CompileType value1, CompileType value2) {
        return value1.codepoint == value2.codepoint;
    }
```

**Comment by ggleyzer** [comment] 2024-11-07 15:19
The problem caused by the fact the generic "const" implementation doesn't know about the specific native Char handle and the corresponding native override was missing. However, I think your solution is absolutely correct, but needs to be also augmented by the fix in the native layer. Working on it...

**Comment by ggleyzer** [comment] 2024-11-07 17:42
Fixed by [this commit](https://github.com/xtclang/xvm/commit/d9ff5a762b63021aa1729da9140a12182342a025)

**Closed by ggleyzer** 2024-11-07 17:42 UTC
